esphome:
  name: esp32-thp
  friendly_name: esp32 - THP
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: back_light
          brightness: 45%   

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8Z08WbkDDtqSURMcIQk4XPboz+ilJXHYAW9kDdt0Kp8="
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - delay: 1s
          # - lvgl.widget.hide: boot_screen
          - lvgl.widget.show: ha_stat_1
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: ha_stat_1    

ota:
  - platform: esphome
    password: "c621e96e3ea7b381db483aa44693c270"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.10.214
    gateway: 192.168.10.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Thp Fallback Hotspot"
    password: "m3WqnDEdrszY"

captive_portal:

web_server:

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/London
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
    on_time_sync:
      - script.execute: time_update    
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update

  - platform: homeassistant
    id: ha_time

script:
  - id: time_update
    then:
      - lvgl.indicator.update:
          id: minute_hand
          value: !lambda |-
            return id(sntp_time).now().minute;

      - lvgl.indicator.update:
          id: hour_hand
          value: !lambda |-
            auto now = id(sntp_time).now();
            return std::fmod(now.hour, 12) * 60 + now.minute;

      # - lvgl.label.update:
      #     id: digi_clock_night
      #     text: !lambda |-
      #       static char time_buf[16];
      #       auto now = id(sntp_time).now();            
      #       snprintf(time_buf, sizeof(time_buf), "%02d:%02d", now.hour, now.minute);
      #       return time_buf;            

external_components:
  - source: github://mcmanigle/esphome-components
    components: ["gc9a01"]

i2c:
  - id: bus_a
    sda: GPIO6
    scl: GPIO7
    scan: true

sensor:
  - platform: uptime
    name: "Uptime"

  - platform: internal_temperature
    name: "Internal Temperature"
    id: int_temp    

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    id: wifi_signal_prc
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

  - platform: sht3xd
    i2c_id: bus_a
    address: 0x44
    update_interval: 30s 
    temperature:
      name: "Temperature sht30"
      id: sht_temp       
      filters:
        - offset: -0.5
      on_value:
        - lvgl.label.update:
            id: label_temp
            text:
              format: "%.1f°"
              args: [ 'x' ]
        - lvgl.label.update:
            id: label_temp_night
            text:
              format: "%.1f°"
              args: [ 'x' ]                              
    humidity:
      name: "Humidity sht30"
      id: sht_hum
      on_value:
        - lvgl.label.update:
            id: label_hum_text
            text:
              format: "Humidity %.0f%%"
              args: [ 'x' ]      

  - platform: absolute_humidity
    name: "Absolute Humidity sht30"
    id: sht_ah
    temperature: sht_temp
    humidity: sht_hum

  - platform: template
    name: "Dew Point sht30"
    id: sht_dp
    lambda: |-
      return (243.5*(log(id(sht_hum).state/100)+((17.67*id(sht_temp).state)/
      (243.5+id(sht_temp).state)))/(17.67-log(id(sht_hum).state/100)-
      ((17.67*id(sht_temp).state)/(243.5+id(sht_temp).state))));
    unit_of_measurement: °C
    icon: 'mdi:thermometer-alert'    

  - platform: qmp6988
    i2c_id: bus_a
    address: 0x70
    update_interval: 31s
    iir_filter: 2x    
    temperature:
      name: "Temperature qmp6988"
      id: qmp_temp
      oversampling: 16x
      filters:
        - offset: -0.8     
    pressure:
      name: "Pressure qmp6988"
      id: qmp_press
      oversampling: 16x
      on_value:
        - lvgl.label.update:
            id: label_press_text
            text:
              format: "Pressure %.0f%"
              args: [ 'x' ]      

  - platform: template
    name: "Altitude qmp6988"
    id: qmp_alt
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
      return ((id(qmp_temp).state + 273.15) / 0.0065) *
        (powf((STANDARD_SEA_LEVEL_PRESSURE / id(qmp_press).state), 0.190234) - 1); // in meter
    update_interval: 15s
    icon: 'mdi:signal'
    unit_of_measurement: 'm'            

binary_sensor:
   - platform: status
     name: "Node Status"
     id: system_status

button:
  - platform: restart
    name: "Restart"
    id: e32r_restart

  - platform: template
    name: "Clock Face Toggle"
    id: clock_toggle
    on_press:
      then:
        - lvgl.page.show: clock_page_night
        - lvgl.page.show: clock_page        

spi:
  mosi_pin: GPIO11
  clk_pin: GPIO10

output:
  - platform: ledc
    pin: GPIO40
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON
    default_transition_length: 3s    

display:
  - platform: ili9xxx
    id: my_lcd
    model: gc9a01a
    reset_pin: GPIO12
    cs_pin: GPIO9
    dc_pin: GPIO8
    # transform: 
    #   swap_xy: true
    #   mirror_x: false
    #   mirror_y: false
    invert_colors: true
    auto_clear_enabled: False
    dimensions: 
      height: 240
      width: 240

lvgl:
  # top_layer:
  #   widgets:
  #     - obj:
  #         id: boot_screen
  #         x: 0
  #         y: 0
  #         width: 100%
  #         height: 100%
  #         bg_color: 0x000000
  #         bg_opa: COVER
  #         radius: 0
  #         pad_all: 0
  #         border_width: 0
  #         widgets:
  #           - spinner:
  #               align: CENTER
  #               y: 0
  #               height: 240
  #               width: 240
  #               spin_time: 3s
  #               arc_length: 60deg
  #               arc_width: 8
  #               arc_rounded: true
  #               arc_opa: 0%
  #               indicator:
  #                 arc_color: my_amber
  #                 arc_width: 8
  #           - label:
  #               text: "\U000F07D1"
  #               text_font: icons_autom
  #               id: ha_icon
  #               align: CENTER
  #               text_color: my_grey

  theme:
    arc:
      arc_color: very_dark_grey_color
      knob:
        bg_color: ice_orange_color
      indicator:
        arc_color: ha_amber
        arc_width: 22
    button:
      text_font: montserrat_18
    label:
      text_font: montserrat_18
      text_color: white_color

  displays:
    - my_lcd

  pages:
    - id: clock_page
      widgets:
        - obj: # clock container
            height: 240
            width: 240
            align: CENTER
            pad_all: 0
            border_width: 0
            bg_color: 0x000000
            widgets:
              - obj:
                  id: ha_stat_1
                  hidden: true                  
                  height: 240
                  width: 240
                  radius: 360
                  align: CENTER
                  border_width: 0
                  pad_all: 0
                  bg_color: 0x343535
              - obj:
                  height: 220
                  width: 220
                  radius: 360
                  align: CENTER
                  border_width: 0
                  pad_all: 0
                  bg_color: 0x000000               
              - meter: # clock face
                  height: 240
                  width: 240
                  align: CENTER
                  bg_opa: TRANSP
                  border_width: 0
                  pad_all: 0
                  text_color: 0xFFFFFF
                  scales:
                    - range_from: 0 # minutes scale
                      range_to: 60
                      angle_range: 360
                      rotation: 270
                      ticks:
                        width: 1
                        count: 61
                        length: 10
                        color: 0xFFFFFF
                      indicators:
                        - line:
                            id: minute_hand
                            width: 3
                            color: ha_amber
                            r_mod: 0
                            value: 0
                    - range_from: 1 # hours scale for labels
                      range_to: 12
                      angle_range: 330
                      rotation: 300
                      ticks:
                        width: 1
                        count: 12
                        length: 1
                        major:
                          stride: 1
                          width: 4
                          length: 10
                          color: 0xC0C0C0
                          label_gap: 12
                    - range_from: 0 # hi-res hours scale for hand
                      range_to: 720
                      angle_range: 360
                      rotation: 270
                      ticks:
                        count: 0
                      indicators:
                        - line:
                            id: hour_hand
                            width: 5
                            color: ha_amber
                            r_mod: -12
                            value: 0
              - obj:
                  height: 180
                  width: 180
                  radius: 360
                  align: CENTER
                  border_width: 0
                  pad_all: 0
                  bg_color: 0x000000

              - obj:
                  id: ha_stat_2
                  # hidden: true                                  
                  height: 175
                  width: 175
                  radius: 360
                  align: CENTER
                  border_width: 0
                  pad_all: 0
                  bg_color: very_dark_grey_color                  

        - label:
            id: label_temp
            text: "-.-°"
            text_font: font1_2
            text_color: 0xFFFFFF
            align: CENTER
            y: -20

        - label:
            id: label_hum_text
            text: "----"
            text_font: montserrat_16
            text_color: my_grey            
            align: CENTER
            y: 32

        - label:
            id: label_press_text
            text: "----"
            text_font: montserrat_16
            text_color: my_grey            
            align: CENTER
            y: 54

    - id: clock_page_night
      widgets:
        - obj: # clock container
            height: 240
            width: 240
            align: CENTER
            pad_all: 0
            border_width: 0
            bg_color: 0x000000
            widgets:
              - obj:
                  height: 180
                  width: 180
                  radius: 360
                  align: CENTER
                  border_width: 0
                  pad_all: 0
                  bg_color: 0x000000

              - label:
                  align: CENTER
                  id: label_temp_night
                  y: -5
                  text: "-.-°"
                  text_font: font1_1
                  text_color: my_red
                  
color:
  - id: white_color
    hex: "FFFFFF"
  - id: very_dark_grey_color
    hex: "272828"
  # - id: light_grey_color
  #   hex: "575858"

  # Green Colors
  # - id: ice_green_color
  #   hex: "8ab65e"
  # - id: ligt_green_color
  #   hex: "6e914b"
  - id: mid_green_color
    hex: "526d38"
  # - id: dark_green_color
  #   hex: "374825"

  # Blue Colors
  # - id: ice_blue_color
  #   hex: "739BD0"
  # - id: light_blue_color
  #   hex: "5c7ca6"
  - id: mid_blue_color
    hex: "455d7c"
  # - id: dark_blue_color
  #   hex: "2e3e53"

  # Orange Colors
  - id: ice_orange_color
    hex: "ef9c5d"
  # - id: light_orange_color
  #   hex: "bf7c4a"
  # - id: mid_orange_color
  #   hex: "8f5d37"
  # - id: dark_orange_color
  #   hex: "5f3e25"
  - id: ha_amber
    hex: "f86f15"
  - id: m5_orange
    hex: "ff860b"

  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_grey
    red: 65%
    green: 65%
    blue: 65%
  - id: my_grey2
    red: 45%
    green: 45%
    blue: 45%
  - id: my_green
    red: 0%
    green: 58%
    blue: 0%
  - id: my_amber
    red: 100%
    green: 43%
    blue: 8%
  - id: ha_blue
    red: 7%
    green: 69%
    blue: 89%

font:
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_autom
    size: 100
    bpp: 4
    glyphs: [
      "\U000F0839", # mdi-tv
      "\U000F0594", # mdi-night
      "\U000F07D1", # mdi-ha
      ]

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_test
    size: 40
    bpp: 4
    glyphs: [
      "\U000F04AB", # mdi-back
      "\U000F040E", # mdi-pp
      "\U000F04AC", # mdi-forward
      ]      

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_other
    size: 30
    bpp: 4
    glyphs: [
      "\U000F07D1", # mdi-ha
      "\U000F05A9", # mdi-wifi
      ]

  # - file: "gfonts://Archivo Black"
  #   id: font2
  #   size: 50

  - file: "gfonts://Concert One"
    id: font1
    size: 50

  - file: "gfonts://Concert One"
    id: font1_1
    size: 92

  - file: "gfonts://Concert One"
    id: font1_2
    size: 58    

  - file: "gfonts://Concert One"
    id: font3
    size: 25  