esphome:
  name: esp32-test
  friendly_name: esp32-test
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: back_light
          brightness: 45% 

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GwtvNper5a+QXfXMjvi5iltDvLN0EH0CBywrT6zeUPQ="

ota:
  - platform: esphome
    password: "af1ea54c8b8d7ec702761c9f1a92f72a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.10.127
    gateway: 192.168.10.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Test Fallback Hotspot"
    password: "V9VnimloJiK8"

captive_portal:

web_server:

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/London
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
    on_time:
      - seconds: /1
        then:
          - lvgl.arc.update:
              id: arc_second
              value: !lambda 'return id(sntp_time).now().second;'
          # - lvgl.label.update:
          #     id: label_second
          #     text: !lambda |-
          #       static char time_buf[16];
          #       auto now = id(sntp_time).now();            
          #       snprintf(time_buf, sizeof(time_buf), "%02d", now.second);
          #       return time_buf;

          - lvgl.arc.update:
              id: arc_minute
              value: !lambda 'return id(sntp_time).now().minute;'
          - lvgl.label.update:
              id: label_minute
              text: !lambda |-
                static char time_buf[16];
                auto now = id(sntp_time).now();            
                snprintf(time_buf, sizeof(time_buf), "%02d", now.minute);
                return time_buf;

          - lvgl.arc.update:
              id: arc_hour
              value: !lambda 'return id(sntp_time).now().hour;'
          - lvgl.label.update:
              id: label_hour
              text: !lambda |-
                static char time_buf[16];
                auto now = id(sntp_time).now();            
                snprintf(time_buf, sizeof(time_buf), "%02d", now.hour);
                return time_buf;                                                                                                      

  - platform: homeassistant
    id: ha_time

external_components:
  - source: github://mcmanigle/esphome-components
    components: ["gc9a01"]

i2c:
  - id: bus_a
    sda: GPIO6
    scl: GPIO7
    scan: true

sensor:
  - platform: uptime
    name: "Uptime"

  - platform: internal_temperature
    name: "Internal Temperature"
    id: int_temp    

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    id: wifi_signal_prc
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

binary_sensor:
   - platform: status
     name: "Node Status"
     id: system_status

button:
  - platform: restart
    name: "Restart"
    id: e32r_restart 

spi:
  mosi_pin: GPIO11
  clk_pin: GPIO10

output:
  - platform: ledc
    pin: GPIO40
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON
    default_transition_length: 3s    

display:
  - platform: ili9xxx
    id: my_lcd
    model: gc9a01a
    reset_pin: GPIO12
    cs_pin: GPIO9
    dc_pin: GPIO8
    # transform: 
    #   swap_xy: true
    #   mirror_x: false
    #   mirror_y: false
    invert_colors: true
    auto_clear_enabled: False
    dimensions: 
      height: 240
      width: 240

lvgl:
  bg_color: 0x000000
  theme:
    arc:
      arc_color: very_dark_grey_color
  widgets:
        - arc:
            id: arc_hour          
            width: 200
            height: 200
            align: CENTER
            arc_width: 8
            arc_rounded: false
            indicator:
              arc_color: my_green
              arc_rounded: false
              arc_width: 8
            value: 0
            min_value: 0
            max_value: 24
            adjustable: false
            start_angle: 0
            end_angle: 360
            rotation: 270

        - meter:
            align: CENTER
            height: 200
            width: 200
            bg_opa: TRANSP
            border_width: 0
            border_color: 0x000000
            border_opa: 0%
            pad_all: 0
            text_opa: 0%
            scales:
              - range_from: 0
                range_to: 24
                angle_range: 360
                rotation: 270
                ticks:
                  width: 3
                  count: 25
                  length: 11
                  color: 0x000000

        - arc:
            id: arc_minute          
            width: 220
            height: 220
            align: CENTER
            arc_width: 8
            arc_rounded: false
            indicator:
              arc_color: 0x2979FF
              arc_rounded: false
              arc_width: 8
            value: 0
            min_value: 0
            max_value: 60
            adjustable: false
            start_angle: 0
            end_angle: 360
            rotation: 270

        - meter:
            align: CENTER
            height: 220
            width: 220
            bg_opa: TRANSP
            border_width: 0
            border_color: 0x000000
            border_opa: 0%
            pad_all: 0
            text_opa: 0%
            scales:
              - range_from: 0
                range_to: 30
                angle_range: 360
                rotation: 270
                ticks:
                  width: 3
                  count: 13
                  length: 10
                  color: 0x000000 

        - arc:
            id: arc_second         
            width: 240
            height: 240
            align: CENTER
            arc_width: 8
            arc_rounded: false
            indicator:
              arc_color: my_amber       
              arc_rounded: false
              arc_width: 8
            value: 0
            min_value: 0
            max_value: 60
            adjustable: false
            start_angle: 0
            end_angle: 360
            rotation: 270

        - meter:
            align: CENTER
            height: 240
            width: 240
            bg_opa: TRANSP
            border_width: 0
            border_color: 0x000000
            border_opa: 0%
            pad_all: 0
            text_opa: 0%
            text_color: my_grey2            
            scales:
              - range_from: 0
                range_to: 30
                angle_range: 360
                rotation: 270
                ticks:
                  width: 3
                  count: 13
                  length: 10
                  color: 0x000000

        - obj:                             
            height: 20
            width: 20
            radius: 360
            align: CENTER
            border_width: 0
            pad_all: 0
            bg_color: 0x000000

        - label:
               id: label_hour
               align: CENTER
               x: 0
               y: -30
               text: "--"
               text_font: font_hour
               text_color: my_grey
               hidden: false                                  

        - label:
               id: label_minute
               align: CENTER
               x: 0
               y: 35
               text: "--"
               text_font: font_minutes
               text_color: my_grey
               hidden: false

color:
  - id: white_color
    hex: "FFFFFF"
  - id: very_dark_grey_color
    hex: "272828"
  - id: light_grey_color
    hex: "575858"

  # Green Colors
  - id: mid_green_color
    hex: "526d38"

  # Blue Colors
  - id: mid_blue_color
    hex: "455d7c"

  # Orange Colors
  - id: ice_orange_color
    hex: "ef9c5d"
  - id: dark_orange_color
    hex: "5f3e25"
  - id: ha_amber
    hex: "f86f15"
  - id: m5_orange
    hex: "ff860b"

  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_grey
    red: 65%
    green: 65%
    blue: 65%
  - id: my_grey2
    red: 45%
    green: 45%
    blue: 45%
  - id: my_green
    red: 0%
    green: 58%
    blue: 0%
  - id: my_amber
    red: 100%
    green: 43%
    blue: 8%
  - id: my_amber2
    hex: "9c2900"    
  - id: ha_blue
    red: 7%
    green: 69%
    blue: 89%

font:
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_50
    size: 50
    bpp: 4
    glyphs: [
      "\U000F0594", # clear-night
      "\U000F0590", # cloudy
      "\U000F0F2F", # exceptional
      "\U000F0591", # fog
      "\U000F0592", # hail
      "\U000F0593", # lightning
      "\U000F067E", # lightning-rainy
      "\U000F0595", # partlycloudy
      "\U000F0596", # pouring
      "\U000F0597", # rainy
      "\U000F0598", # snowy
      "\U000F067F", # snowy-rainy
      "\U000F0599", # sunny
      "\U000F059D", # windy
      "\U000F059E", # windy-variant
      "\U000F14E4", # sunny-off
      ]

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_autom
    size: 100
    bpp: 4
    glyphs: [
      "\U000F0839", # mdi-tv
      "\U000F0594", # mdi-night
      "\U000F07D1", # mdi-ha
      ]

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_test
    size: 40
    bpp: 4
    glyphs: [
      "\U000F04AB", # mdi-back
      "\U000F040E", # mdi-pp
      "\U000F04AC", # mdi-forward
      ]      

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_other
    size: 30
    bpp: 4
    glyphs: [
      "\U000F07D1", # mdi-ha
      "\U000F05A9", # mdi-wifi
      ]

  # - file: "gfonts://Archivo Black"
  #   id: font2
  #   size: 50

  - file: "gfonts://Concert One"
    id: font1
    size: 50

  - file: "gfonts://Concert One"
    id: font3
    size: 25

  - file: "fonts/Inter-Regular.otf"
    id: font11
    size: 25
    bpp: 4  

  - file: "fonts/Roboto-Bold.ttf"
    id: font12
    size: 35
    bpp: 4

  - file: "fonts/Roboto-Bold.ttf"
    id: font1_1
    size: 80

  - file: "gfonts://Orbitron@700"
    id: font_hour
    size: 66
    bpp: 4

  - file: "gfonts://Orbitron@400"
    id: font_minutes
    size: 48
    bpp: 4                

    